# Generated by Django 2.1.3 on 2018-11-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPrice',
            new_name='Products',
        ),
    ]
